// <auto-generated />
using System;
using Gaming_store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gaming_store.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260601060038_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gaming_store.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Gaming_store.Entities.CartGame", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("CartId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("CartGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("image")
                        .IsRequired()
                        .HasColumnType("image");

                    b.HasKey("Id");

                    b.ToTable("Games", t =>
                        {
                            t.HasCheckConstraint("Game_Price_CK", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("Gaming_store.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Gaming_store.Entities.LibraryGame", b =>
                {
                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("LibraryId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("LibraryGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("User_Balance_CK", "[Balance] >= 0");
                        });
                });

            modelBuilder.Entity("Gaming_store.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Gaming_store.Entities.WishlistGame", b =>
                {
                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("WishlistGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.Cart", b =>
                {
                    b.HasOne("Gaming_store.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Gaming_store.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gaming_store.Entities.CartGame", b =>
                {
                    b.HasOne("Gaming_store.Entities.Cart", "Cart")
                        .WithMany("CartsGames")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gaming_store.Entities.Game", "Game")
                        .WithMany("CartsGames")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Gaming_store.Entities.Library", b =>
                {
                    b.HasOne("Gaming_store.Entities.User", "User")
                        .WithOne("Library")
                        .HasForeignKey("Gaming_store.Entities.Library", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gaming_store.Entities.LibraryGame", b =>
                {
                    b.HasOne("Gaming_store.Entities.Game", "Game")
                        .WithMany("LibrariesGames")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("Gaming_store.Entities.Library", "Library")
                        .WithMany("LibrariesGames")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Gaming_store.Entities.Wishlist", b =>
                {
                    b.HasOne("Gaming_store.Entities.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("Gaming_store.Entities.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gaming_store.Entities.WishlistGame", b =>
                {
                    b.HasOne("Gaming_store.Entities.Game", "Game")
                        .WithMany("WishlistsGames")
                        .HasForeignKey("GameId")
                        .IsRequired();

                    b.HasOne("Gaming_store.Entities.Wishlist", "Wishlist")
                        .WithMany("WishlistsGames")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Gaming_store.Entities.Cart", b =>
                {
                    b.Navigation("CartsGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.Game", b =>
                {
                    b.Navigation("CartsGames");

                    b.Navigation("LibrariesGames");

                    b.Navigation("WishlistsGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.Library", b =>
                {
                    b.Navigation("LibrariesGames");
                });

            modelBuilder.Entity("Gaming_store.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Library")
                        .IsRequired();

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("Gaming_store.Entities.Wishlist", b =>
                {
                    b.Navigation("WishlistsGames");
                });
#pragma warning restore 612, 618
        }
    }
}
